### ISSUE TITLE
Could I visualize the training process without --render?

### ISSUE THREAD

**Issue by encorechow** [openai/neural-mmo#14]
Hi, thanks for opensource this excellent work! I have tried the example and it works very well with --render. When I digged into the code, with opening render option, it seems the client code was invoked, and I had trouble to find the training process in the render code. Without render, I got the path of training procedure.   but running without render always stuck in ```run``` function of ```NtiveRealm``` because the update would always be ```None```, and program fall into the endless loop. I am trying to figure out if there is a API that I can observe the training process without --render option on? Thank you very much!

**Comment by jsuarez5341** [comment]
Hi! Yes, run() will keep looping forever. Take a look at the readme. The native API provides three classes in forge/trinity which you can subclass in order to interact with the environment. For the example code, cluster level operations (aggregating gradients, running Adam to update weights) run in Pantheon. Environment level operations run in God (you can mostly ignore this one). The main agent code is in Sword. Note that test mode is set to true by default to prevent people from accidentally overriding the trained policies that ship with the environment. You can set up training specifications in experiments.py. There is also a figures.py for visualizing training statistics, if you don't want to load the full client. Please feel free to let me know how else I can help.
