### ISSUE TITLE
Frames Per Second Per Core?

### ISSUE THREAD

**Issue by kumarict** [openai/neural-mmo#24]
(Note: This is a question, not a bug or issue with function/performance! Also, wasn't sure where else to ask this, so apologies if this is the wrong place - kindly let me know the proper place if there is one!)

I found that Facebook ELF (https://github.com/facebookresearch/ELF) lists the number of (AI) frames per second per core (40k). What is the frames per second per core for Neural MMO? When running this code, how many cores are used? Thank you.

Thank you to everyone who worked on this. This is quite amazing and you should all be proud of the great work you have done!

**Comment by jsuarez5341** [comment]
Hello! This is the correct place for questions for now -- I'll likely be implementing something better concurrent with the first major patch.  I actually do not know this off the top of my head because training is done on the same cores as the environment. I am working on an update that will make it easier to swap in/out models -- once I have a random agent or the like, I should be able to provide a better estimate. I'll leave this open for now so I remember to do this :)

**Comment by jsuarez5341** [comment]
Update after a very long time: it's dependent on your policy. The better the model is doing, the more agents coexist in the world. The unfair estimate is 250k/second/core for ~50 concurrent agents. If we were comparing to single agent environments, you'd multiply and get ~1.25m frames/second/core. This is from a quick observation of the new logging code -- let me know if you think I've missed the mark.

In practice: the environment is very unoptimized, but it's built such that it requires very little computation in the first place. Training/communication are always the bottlenecks. In my work, I end up just sticking it on the same cores as the rollout workers, and it only takes around 2% of the cpu time.
