### ISSUE TITLE
Agents don't attack each other

### ISSUE THREAD

**Issue by pys16** [openai/neural-mmo#35]
when I run with NPOP=2(or more), NENT=128 and --render, I never see the agents attacking each other during my whole observation. I'm still new to this project, and the only attempt I've made is to change the root in forge.ethyr.torch.io.action.leaves from _action.Move_ to _action.Action_ or _action.Attack_, but it ends up with errors like "list index out of range". Should I modify the action and the network myself, or is that any simple way I can make them combat like in the demo?

**Comment by jsuarez5341** [comment]
You're correct -- the v1.1 update focused on infrastructure, not the demo model.

The 1.1 model is a weak foraging (no combat) baseline. The environment has the same attack functionality as v1.0, but for the time being, you'd have to either write your own action selection code for that or fix up the partially complete attack demo in forge.ethyr.io.action.leaves.

This is, of course, on my todo list. However, I'm currently taking a break from the server code in order to touch up the front-end for the next development pass.

In the meanwhile, I can provide plenty of support over on our Discord channel (https://discordapp.com/invite/BkMmFUC). This is also the best place to get the most up-to-date information on the development of the project.
